--[[
    RITMINITY - Song Select Screen
    Pantalla de selección de canciones
]]

local SongSelect = {}
SongSelect.__index = SongSelect

local ChartParser = require("src.loaders.chart_parser")
local StateManager = require("src.core.state")
local AIGenerator = require("src.utils.ai_generator")
local AudioManager = require("src.managers.audio_manager")

-- Canciones disponibles
SongSelect.songs = {}

-- Estado
SongSelect.selectedIndex = 1
SongSelect.scrollOffset = 0
SongSelect.previewPlaying = false
SongSelect.parser = nil

function SongSelect:init()
    self.parser = ChartParser:new()
    self.ai = AIGenerator:new()
    self.generating = false
    self.generateTimer = 0
    self.songToGenerate = nil
    self:scanSongs()
end

function SongSelect:scanSongs()
    self.songs = {}
    local songsDir = "assets/songs"
    
    if not love.filesystem.getInfo(songsDir) then
        love.filesystem.createDirectory(songsDir)
    end
    
    local items = love.filesystem.getDirectoryItems(songsDir)
    local idCounter = 1
    
    for _, item in ipairs(items) do
        local dirPath = songsDir .. "/" .. item
        local info = love.filesystem.getInfo(dirPath)
        
        if info and info.type == "directory" then
            local files = love.filesystem.getDirectoryItems(dirPath)
            for _, file in ipairs(files) do
                if file:match("%.osu$") or file:match("%.sm$") then
                    local fullPath = dirPath .. "/" .. file
                    local chart, err = self.parser:parseFile(fullPath)
                    
                    if chart then
                        local internalChart = self.parser:convertToInternal(chart, 4)
                        
                        -- Arreglar ruta relativa del audio
                        if internalChart.audioFile then
                            internalChart.audioFile = dirPath .. "/" .. internalChart.audioFile
                        end
                        
                        local length = 0
                        if #internalChart.notes > 0 then
                            length = internalChart.notes[#internalChart.notes].time
                        end
                        
                        table.insert(self.songs, {
                            id = idCounter,
                            title = internalChart.title,
                            artist = internalChart.artist,
                            bpm = internalChart.bpm,
                            difficulty = internalChart.difficulty or "Normal",
                            length = length,
                            chartData = internalChart,
                            isAutoGenerated = false
                        })
                        idCounter = idCounter + 1
                    end
                elseif file:match("%.mp3$") or file:match("%.ogg$") then
                    local fullPath = dirPath .. "/" .. file
                    table.insert(self.songs, {
                        id = idCounter,
                        title = file:match("([^/\\]+)%.%w+$") or file,
                        artist = "IA Auto-Mapper",
                        bpm = "?",
                        difficulty = "Auto",
                        length = 0,
                        chartData = nil,
                        audioFile = fullPath,
                        isAutoGenerated = true
                    })
                    idCounter = idCounter + 1
            end
        end
        end -- Cerrar if info.type == "directory"
        -- Check for individual files (not in directories)
        if info and info.type == "file" then
            if item:match("%.mp3$") or item:match("%.ogg$") then
                local fullPath = songsDir .. "/" .. item
                table.insert(self.songs, {
                    id = idCounter,
                    title = item:match("([^/\\]+)%.%w+$") or item,
                    artist = "IA Auto-Mapper",
                    bpm = "?",
                    difficulty = "Auto",
                    length = 0,
                    chartData = nil,
                    audioFile = fullPath,
                    isAutoGenerated = true
                })
                idCounter = idCounter + 1
            end
        end
    end
    
    if #self.songs == 0 then
        table.insert(self.songs, {
            id = 1, 
            title = "Sin mapas instalados", 
            artist = "Añade archivos .osu en assets/songs/", 
            bpm = 0, 
            difficulty = "-", 
            length = 0, 
            chartData = nil
        })
    end
end

function SongSelect:enter(params)
    self.selectedIndex = 1
    self.scrollOffset = 0
    self.previewMusic = nil
    self.previewTimer = 0
    
    -- Iniciar preview de la primera canción si existe
    self:updatePreview()
end

function SongSelect:exit()
    AudioManager:stopMusic()
end

function SongSelect:updatePreview()
    local song = self.songs[self.selectedIndex]
    if not song then return end
    
    local audioFile = song.audioFile or (song.chartData and song.chartData.audioFile)
    
    if audioFile then
        -- Detener música actual
        AudioManager:stopMusic()
        
        -- Cargar y reproducir preview (un poco más de volumen)
        local music = AudioManager:loadMusic(audioFile)
        if music then
            -- Empezar desde el punto de preview si existe (osu style) o desde el 30%
            local duration = music:getDuration()
            music:seek(duration * 0.3) 
            AudioManager:playMusic(music, 0.6)
            self.previewMusic = music
        end
    end
end

function SongSelect:update(dt)
    if self.generating and self.songToGenerate then
        self.generateTimer = self.generateTimer - dt
        if self.generateTimer <= 0 then
            local chart = self.ai:generateFromAudio(self.songToGenerate.audioFile)
            if chart then
                self.songToGenerate.chartData = chart
                self.songToGenerate.bpm = chart.metadata.bpm
                StateManager:change("gameplay", {
                    song = self.songToGenerate,
                    chart = chart,
                    columnCount = chart.columnCount or 4,
                    from = "songselect"
                })
            end
            self.generating = false
            self.songToGenerate = nil
        end
        return
    end

    -- Smooth Scrolling
    local targetOffset = (self.selectedIndex - 1) * 90 - 250
    self.scrollOffset = self.scrollOffset + (targetOffset - self.scrollOffset) * 10 * dt
end

function SongSelect:draw()
    -- Fondo con gradiente oscuro
    love.graphics.setColor(0.02, 0.02, 0.05, 1)
    love.graphics.rectangle("fill", 0, 0, 1280, 720)
    
    -- Dibujar lista (Derecha)
    local listX = 700
    local startY = 360 - self.scrollOffset
    
    for i, song in ipairs(self.songs) do
        local y = startY + (i - 1) * 90
        local selected = (i == self.selectedIndex)
        
        -- Solo dibujar si es visible
        if y > -100 and y < 800 then
            local alpha = selected and 1.0 or 0.6
            local xOffset = selected and -40 or 0
            
            -- Fondo del item
            if selected then
                love.graphics.setColor(0.2, 0.6, 1, 0.4)
                love.graphics.rectangle("fill", listX + xOffset, y, 600, 80, 4, 4)
                love.graphics.setColor(1, 1, 1, 1)
                love.graphics.rectangle("line", listX + xOffset, y, 600, 80, 4, 4)
            else
                love.graphics.setColor(0.1, 0.1, 0.15, 0.8)
                love.graphics.rectangle("fill", listX + 5, y + 5, 580, 70, 4, 4)
            end
            
            -- Texto
            love.graphics.setFont(love.graphics.newFont(22))
            love.graphics.setColor(1, 1, 1, alpha)
            love.graphics.print(song.title, listX + xOffset + 30, y + 15)
            
            love.graphics.setFont(love.graphics.newFont(14))
            love.graphics.setColor(0.7, 0.7, 0.7, alpha)
            love.graphics.print(song.artist or "Unknown Artist", listX + xOffset + 30, y + 45)
            
            -- Dificultad (Badge)
            if song.difficulty then
                love.graphics.setColor(0.3, 0.8, 1, alpha)
                love.graphics.rectangle("fill", listX + xOffset + 500, y + 25, 80, 30, 15, 15)
                love.graphics.setColor(0, 0, 0, alpha)
                love.graphics.setFont(love.graphics.newFont(12))
                love.graphics.printf(song.difficulty, listX + xOffset + 500, y + 33, 80, "center")
            end
        end
    end
    
    -- Panel de Información (Izquierda) - Estilo Etterna
    self:drawSongInfo()
end

function SongSelect:drawSongInfo()
    local song = self.songs[self.selectedIndex]
    if not song then return end
    
    local panelX = 50
    local panelY = 100
    
    -- Título Grande
    love.graphics.setFont(love.graphics.newFont(48))
    love.graphics.setColor(1, 1, 1, 1)
    love.graphics.printf(song.title, panelX, panelY, 600, "left")
    
    love.graphics.setFont(love.graphics.newFont(24))
    love.graphics.setColor(0.6, 0.8, 1, 1)
    love.graphics.printf(song.artist or "Unknown Artist", panelX, panelY + 60, 600, "left")
    
    -- Caja de Metadatos
    love.graphics.setColor(0.1, 0.1, 0.2, 0.5)
    love.graphics.rectangle("fill", panelX, panelY + 120, 400, 200, 8, 8)
    
    love.graphics.setFont(love.graphics.newFont(18))
    love.graphics.setColor(0.8, 0.8, 0.8, 1)
    local metaY = panelY + 140
    love.graphics.print("BPM: " .. tostring(song.bpm), panelX + 20, metaY)
    love.graphics.print("Length: " .. string.format("%d:%02d", math.floor(song.length / 60), song.length % 60), panelX + 20, metaY + 30)
    love.graphics.print("Difficulty: " .. song.difficulty, panelX + 20, metaY + 60)
    
    -- Instrucciones
    love.graphics.setFont(love.graphics.newFont(16))
    love.graphics.setColor(0.4, 0.4, 0.4, 1)
    love.graphics.printf("↑/↓: Seleccionar  |  Enter: Jugar  |  Esc: Menú", panelX, 650, 600, "left")
end

function SongSelect:onEscape()
    StateManager:change("mainmenu")
end

function SongSelect:handleInput(key)
    if key == "up" or key == "w" then
        self.selectedIndex = self.selectedIndex - 1
        if self.selectedIndex < 1 then
            self.selectedIndex = #self.songs
        end
        self:updatePreview()
    elseif key == "down" or key == "s" then
        self.selectedIndex = self.selectedIndex + 1
        if self.selectedIndex > #self.songs then
            self.selectedIndex = 1
        end
        self:updatePreview()
    elseif key == "return" or key == "enter" or key == "kpenter" or key == "space" then
        if self.generating then return end
        
        -- Iniciar juego con la canción seleccionada
        local song = self.songs[self.selectedIndex]
        if song then
            if song.isAutoGenerated then
                self.generating = true
                self.songToGenerate = song
                self.generateTimer = 0.1 -- Dar 0.1s para que se dibuje el frame de carga
            elseif song.chartData then
                StateManager:change("gameplay", {
                    song = song,
                    chart = song.chartData,
                    from = "songselect"
                })
            end
        end
    elseif key == "escape" then
        self:onEscape()
    end
end

function SongSelect:mousemoved(x, y, dx, dy)
    local listX = 700
    local startY = 360 - self.scrollOffset
    for i, song in ipairs(self.songs) do
        local optY = startY + (i - 1) * 90
        if x >= listX and x <= listX + 600 and y >= optY and y <= (optY + 85) then
            if self.selectedIndex ~= i then
                self.selectedIndex = i
                self:updatePreview()
            end
            break
        end
    end
end

function SongSelect:mousepressed(x, y, button)
    if button == 1 then
        local listX = 700
        local startY = 360 - self.scrollOffset
        for i, song in ipairs(self.songs) do
            local optY = startY + (i - 1) * 90
            if x >= listX and x <= listX + 600 and y >= optY and y <= (optY + 85) then
                if self.generating then return end
                
                if self.selectedIndex == i then
                    local s = self.songs[self.selectedIndex]
                    if s then
                        if s.isAutoGenerated then
                            self.generating = true
                            self.songToGenerate = s
                            self.generateTimer = 0.1
                        elseif s.chartData then
                            StateManager:change("gameplay", {
                                song = s,
                                chart = s.chartData,
                                from = "songselect"
                            })
                        end
                    end
                else
                    self.selectedIndex = i
                    self:updatePreview()
                end
                break
            end
        end
    end
end

return SongSelect