--[[
    RITMINITY - Song Select Screen
    Pantalla de selección de canciones
]]

local SongSelect = {}
SongSelect.__index = SongSelect

local ChartParser = require("src.chart.parser")
local StateManager = require("src.core.state")
local AIGenerator = require("src.ai.generator")

-- Canciones disponibles
SongSelect.songs = {}

-- Estado
SongSelect.selectedIndex = 1
SongSelect.scrollOffset = 0
SongSelect.previewPlaying = false
SongSelect.parser = nil

function SongSelect:init()
    self.parser = ChartParser:new()
    self.ai = AIGenerator:new()
    self.generating = false
    self.generateTimer = 0
    self.songToGenerate = nil
    self:scanSongs()
end

function SongSelect:scanSongs()
    self.songs = {}
    local songsDir = "assets/songs"
    
    if not love.filesystem.getInfo(songsDir) then
        love.filesystem.createDirectory(songsDir)
    end
    
    local items = love.filesystem.getDirectoryItems(songsDir)
    local idCounter = 1
    
    for _, item in ipairs(items) do
        local dirPath = songsDir .. "/" .. item
        local info = love.filesystem.getInfo(dirPath)
        
        if info and info.type == "directory" then
            local files = love.filesystem.getDirectoryItems(dirPath)
            for _, file in ipairs(files) do
                if file:match("%.osu$") or file:match("%.sm$") then
                    local fullPath = dirPath .. "/" .. file
                    local chart, err = self.parser:parseFile(fullPath)
                    
                    if chart then
                        local internalChart = self.parser:convertToInternal(chart, 4)
                        
                        -- Arreglar ruta relativa del audio
                        if internalChart.audioFile then
                            internalChart.audioFile = dirPath .. "/" .. internalChart.audioFile
                        end
                        
                        local length = 0
                        if #internalChart.notes > 0 then
                            length = internalChart.notes[#internalChart.notes].time
                        end
                        
                        table.insert(self.songs, {
                            id = idCounter,
                            title = internalChart.title,
                            artist = internalChart.artist,
                            bpm = internalChart.bpm,
                            difficulty = chart.difficulty and chart.difficulty.Version or "Normal",
                            length = length,
                            chartData = internalChart,
                            isAutoGenerated = false
                        })
                        idCounter = idCounter + 1
                    end
                elseif file:match("%.mp3$") or file:match("%.ogg$") then
                    local fullPath = dirPath .. "/" .. file
                    table.insert(self.songs, {
                        id = idCounter,
                        title = file:match("([^/\\]+)%.%w+$") or file,
                        artist = "IA Auto-Mapper",
                        bpm = "?",
                        difficulty = "Auto",
                        length = 0,
                        chartData = nil,
                        audioFile = fullPath,
                        isAutoGenerated = true
                    })
                    idCounter = idCounter + 1
            end
        end
        
        -- Check for individual files (not in directories)
        if info and info.type == "file" then
            if item:match("%.mp3$") or item:match("%.ogg$") then
                local fullPath = songsDir .. "/" .. item
                table.insert(self.songs, {
                    id = idCounter,
                    title = item:match("([^/\\]+)%.%w+$") or item,
                    artist = "IA Auto-Mapper",
                    bpm = "?",
                    difficulty = "Auto",
                    length = 0,
                    chartData = nil,
                    audioFile = fullPath,
                    isAutoGenerated = true
                })
                idCounter = idCounter + 1
            end
        end
    end
    
    if #self.songs == 0 then
        table.insert(self.songs, {
            id = 1, 
            title = "Sin mapas instalados", 
            artist = "Añade archivos .osu en assets/songs/", 
            bpm = 0, 
            difficulty = "-", 
            length = 0, 
            chartData = nil
        })
    end
end

function SongSelect:enter(params)
    self.selectedIndex = 1
    self.scrollOffset = 0
end

function SongSelect:exit()
end

function SongSelect:update(dt)
    if self.generating and self.songToGenerate then
        self.generateTimer = self.generateTimer - dt
        if self.generateTimer <= 0 then
            -- Generar el mapa ahora que ya dibujamos el frame de "Generando..."
            local chart = self.ai:generateFromAudio(self.songToGenerate.audioFile)
            if chart then
                self.songToGenerate.chartData = chart
                self.songToGenerate.bpm = chart.metadata.bpm
                self.songToGenerate.isAutoGenerated = false
                
                StateManager:change("gameplay", {
                    song = self.songToGenerate,
                    chart = chart
                })
            else
                print("Error: No se pudo auto-generar la canción.")
            end
            self.generating = false
            self.songToGenerate = nil
        end
        return -- No procesar scroll mientras genera
    end

    -- Auto-scroll para mantener selección visible
    local targetOffset = (self.selectedIndex - 1) * 80 - 200
    self.scrollOffset = self.scrollOffset + (targetOffset - self.scrollOffset) * 0.1
end

function SongSelect:draw()
    -- Fondo
    love.graphics.setColor(0.05, 0.05, 0.1, 1)
    love.graphics.rectangle("fill", 0, 0, 1280, 720)
    
    -- Título
    love.graphics.setFont(love.graphics.newFont(30))
    love.graphics.setColor(1, 1, 1, 1)
    love.graphics.printf("Selección de Canción", 0, 50, 1280, "center")
    
    -- Lista de canciones
    local startY = 150 - self.scrollOffset
    
    for i, song in ipairs(self.songs) do
        local y = startY + (i - 1) * 80
        local selected = (i == self.selectedIndex)
        
        -- Fondo de canción
        if selected then
            love.graphics.setColor(0.2, 0.6, 1, 0.3)
            love.graphics.rectangle("fill", 140, y, 1000, 70)
        else
            love.graphics.setColor(0.1, 0.1, 0.15, 1)
            love.graphics.rectangle("fill", 150, y + 5, 980, 60)
        end
        
        -- Número
        love.graphics.setFont(love.graphics.newFont(20))
        love.graphics.setColor(0.5, 0.5, 0.5, 1)
        love.graphics.print(string.format("%02d", song.id), 180, y + 20)
        
        -- Título
        love.graphics.setFont(love.graphics.newFont(24))
        if selected then
            love.graphics.setColor(1, 1, 1, 1)
        else
            love.graphics.setColor(0.8, 0.8, 0.8, 1)
        end
        love.graphics.print(song.title, 240, y + 15)
        
        -- Artista
        love.graphics.setFont(love.graphics.newFont(16))
        love.graphics.setColor(0.6, 0.6, 0.6, 1)
        love.graphics.print(song.artist, 240, y + 42)
        
        -- Info (BPM, Difficulty, Length)
        love.graphics.setFont(love.graphics.newFont(14))
        love.graphics.setColor(0.5, 0.5, 0.5, 1)
        local info = string.format("BPM: %d  |  %s  |  %d:%02d", song.bpm, song.difficulty, math.floor(song.length / 60), song.length % 60)
        love.graphics.print(info, 850, y + 25)
    end
    
    -- Información de la canción seleccionada
    local song = self.songs[self.selectedIndex]
    if song then
        love.graphics.setColor(0.1, 0.1, 0.1, 0.8)
        love.graphics.rectangle("fill", 140, 600, 1000, 100)
        
        love.graphics.setFont(love.graphics.newFont(20))
        love.graphics.setColor(1, 1, 1, 1)
        if song.isAutoGenerated then
            love.graphics.setColor(0.3, 1, 0.5, 1)
            love.graphics.printf("Presiona Enter para Auto-Generar el nivel (IA)", 0, 650, 1280, "center")
        else
            love.graphics.printf("Presiona Enter o haz clic para jugar", 0, 650, 1280, "center")
        end
        
        love.graphics.setFont(love.graphics.newFont(14))
        love.graphics.setColor(0.5, 0.5, 0.5, 1)
        love.graphics.printf("←→: Cambiar columnas  |  Tab: Mods", 0, 680, 1280, "center")
    end

    -- Pantalla de carga
    if self.generating then
        love.graphics.setColor(0, 0, 0, 0.8)
        love.graphics.rectangle("fill", 0, 0, 1280, 720)
        
        love.graphics.setFont(love.graphics.newFont(40))
        love.graphics.setColor(1, 1, 1, 1)
        love.graphics.printf("Analizando audio...", 0, 320, 1280, "center")
        
        love.graphics.setFont(love.graphics.newFont(20))
        love.graphics.setColor(0.5, 0.8, 1, 1)
        love.graphics.printf("Detectando ritmos y mapeando notas (Esto puede tardar unos segundos)", 0, 380, 1280, "center")
    end
end

function SongSelect:onEscape()
    StateManager:change("mainmenu")
end

function SongSelect:handleInput(key)
    if key == "up" or key == "w" then
        self.selectedIndex = self.selectedIndex - 1
        if self.selectedIndex < 1 then
            self.selectedIndex = #self.songs
        end
    elseif key == "down" or key == "s" then
        self.selectedIndex = self.selectedIndex + 1
        if self.selectedIndex > #self.songs then
            self.selectedIndex = 1
        end
    elseif key == "return" or key == "enter" then
        if self.generating then return end
        
        -- Iniciar juego con la canción seleccionada
        local song = self.songs[self.selectedIndex]
        if song then
            if song.isAutoGenerated then
                self.generating = true
                self.songToGenerate = song
                self.generateTimer = 0.1 -- Dar 0.1s para que se dibuje el frame de carga
            elseif song.chartData then
                StateManager:change("gameplay", {
                    song = song,
                    chart = song.chartData
                })
            end
        end
    end
end

function SongSelect:mousemoved(x, y, dx, dy)
    local startY = 150 - self.scrollOffset
    for i, song in ipairs(self.songs) do
        local optY = startY + (i - 1) * 80
        if x >= 140 and x <= 1140 and y >= optY and y <= (optY + 70) then
            self.selectedIndex = i
            break
        end
    end
end

function SongSelect:mousepressed(x, y, button)
    if button == 1 then
        local startY = 150 - self.scrollOffset
        for i, song in ipairs(self.songs) do
            local optY = startY + (i - 1) * 80
            if x >= 140 and x <= 1140 and y >= optY and y <= (optY + 70) then
                if self.generating then return end
                
                if self.selectedIndex == i then
                    local s = self.songs[self.selectedIndex]
                    if s then
                        if s.isAutoGenerated then
                            self.generating = true
                            self.songToGenerate = s
                            self.generateTimer = 0.1
                        elseif s.chartData then
                            StateManager:change("gameplay", {
                                song = s,
                                chart = s.chartData
                            })
                        end
                    end
                else
                    self.selectedIndex = i
                end
                break
            end
        end
    end
end

return SongSelect